---
networks:
  lbetz.localdomain:
    :address: 192.168.5.0
machines:
  ruby:
    :os: Debian10
    :net:
      lbetz.localdomain:
        :ip: 192.168.5.10
    :shared:
      '~/puppetcode/development': /root/puppetcode
      '~/rubycode': /root/rubycode

  centos7:
    :os: Centos7
    :net:
      lbetz.localdomain:
        :ip: 192.168.5.12
    :shared:
      '~/puppetcode/development': /root/puppetcode
  centos8:
    :os: Centos8
    :net:
      lbetz.localdomain:
        :ip: 192.168.5.13
    :shared:
      '~/puppetcode/development': /root/puppetcode
  alma8:
    :os: AlmaLinux8
    :net:
      lbetz.localdomain:
        :ip: 192.168.5.14
    :shared:
      '~/puppetcode/development': /root/puppetcode
  rocky8:
    :os: RockyLinux8
    :net:
      lbetz.localdomain:
        :ip: 192.168.5.15
    :shared:
      '~/puppetcode/development': /root/puppetcode
  oracle8:
    :memory: 2048
    :cpu: 2
    :os: Oracle8
    :net:
      lbetz.localdomain:
        :ip: 192.168.5.17
    :shared:
      '~/puppetcode/development': /root/puppetcode
  debian9:
    :os: Debian9
    :net:
      lbetz.localdomain:
        :ip: 192.168.5.22
    :shared:
      '~/puppetcode/development': /root/puppetcode
  debian10:
    :os: Debian10
    :net:
      lbetz.localdomain:
        :ip: 192.168.5.23
    :shared:
      '~/puppetcode/development': /root/puppetcode
  debian11:
    :os: Debian11
    :memory: 1024
    :net:
      lbetz.localdomain:
        :ip: 192.168.5.24
    :shared:
      '~/puppetcode/development': /root/puppetcode
  ubuntu18:
    :os: Ubuntu18
    :net:
      lbetz.localdomain:
        :ip: 192.168.5.32
    :shared:
      '~/puppetcode/development': /root/puppetcode
  ubuntu20:
    :os: Ubuntu20
    :memory: 4096
    :net:
      lbetz.localdomain:
        :ip: 192.168.5.33
    :shared:
      '~/puppetcode/development': /root/puppetcode
  ubuntu22:
    :os: Ubuntu22
    :memory: 1024
    :net:
      lbetz.localdomain:
        :ip: 192.168.5.34
    :shared:
      '~/puppetcode/development': /root/puppetcode
  suse15:
    :os: Suse15
    :net:
      lbetz.localdomain:
        :ip: 192.168.5.42
    :shared:
      '~/puppetcode/development': /root/puppetcode
  w2k16:
    :os: Windows2016
    :cpu: 2
    :memory: 4096
    :net:
      lbetz.localdomain:
        :ip: 192.168.5.52
    :shared:
      '~/puppetcode/development': C:/puppetcode
  w2k19:
    :os: Windows2019
    :cpu: 2
    :memory: 2048
    :net:
      lbetz.localdomain:
        :ip: 192.168.5.53
    :shared:
      '~/puppetcode/development': C:/puppetcode
  fedora32:
    :os: Fedora32
    :net:
      lbetz.localdomain:
        :ip: 192.168.5.62
    :shared:
      '~/puppetcode/development': /root/puppetcode

operatingsystems:
  RedHat8:
    :family: redhat
    :name: redhat
    :release: 8
    :box: generic/rhel8
  Centos6:
    :family: redhat
    :name: centos
    :release: 6
    :box: bento/centos-6
  Centos7:
    :family: redhat
    :name: centos
    :release: 7
    :box: bento/centos-7
  Centos8:
    :family: redhat
    :name: centos
    :release: 8
    :box: bento/centos-stream-8
  AlmaLinux8:
    :family: redhat
    :name: almalinux
    :release: 8
    :box: bento/almalinux-8
  AlmaLinux9:
    :family: redhat
    :name: almalinux
    :release: 9
    :box: bento/almalinux-9
  RockyLinux8:
    :family: redhat
    :name: rockylinux
    :release: 8
    :box: bento/rockylinux-8
  RockyLinux9:
    :family: redhat
    :name: rockylinux
    :release: 9
    :box: bento/rockylinux-9
  Scientific7:
    :family: redhat
    :name: scientific
    :release: 7
    :box: bento/scientific-7
  Oracle7:
    :family: redhat
    :name: oraclelinux
    :release: 7
    :box: bento/oracle-7
  Oracle8:
    :family: redhat
    :name: oraclelinux
    :release: 8
    :box: bento/oracle-8
  Fedora34:
    :family: redhat
    :name: fedora
    :release: 34
    :box: bento/fedora-34
  Fedora33:
    :family: redhat
    :name: fedora
    :release: 33
    :box: bento/fedora-33
  Fedora32:
    :family: redhat
    :name: fedora
    :release: 32
    :box: bento/fedora-32
  Debian8:
    :family: debian
    :name: debian
    :release: jessie
    :box: bento/debian-8
  Debian9:
    :family: debian
    :name: debian
    :release: stretch
    :box: bento/debian-9
  Debian10:
    :family: debian
    :name: debian
    :release: buster
    :box: bento/debian-10
  Debian11:
    :family: debian
    :name: debian
    :release: bullseye
    :box: bento/debian-11
  Ubuntu16:
    :family: debian
    :name: ubuntu
    :release: xenial
    :box: bento/ubuntu-16.04
  Ubuntu18:
    :family: debian
    :name: ubuntu
    :release: bionic
    :box: bento/ubuntu-18.04
  Ubuntu20:
    :family: debian
    :name: ubuntu
    :release: focal
    :box: bento/ubuntu-20.04
  Ubuntu22:
    :family: debian
    :name: ubuntu
    :release: jammy
    :box: bento/ubuntu-22.04
  Suse12:
    :family: suse
    :name: opensuse
    :release: 12
    :box: bento/opensuse-leap-42
  Suse15:
    :family: suse
    :name: opensuse
    :release: 15
    :box: bento/opensuse-leap-15.3
  Windows2016:
    :family: windows
    :name: windows
    :release: 2016
    :box: tas50/windows_2016
  Windows2019:
    :family: windows
    :name: windows
    :release: 2019
    :box: tas50/windows_2019
