mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs/apt'
mod 'richardc/datacat'
mod 'puppet/extlib'
mod 'puppetlabs/hocon'
mod 'puppetlabs/inifile'
mod 'puppetlabs/puppet_authorization'

mod 'theforeman/puppet'
mod 'puppetlabs/puppetdb'
mod 'puppetlabs/postgresql'
mod 'theforeman/dns'
mod 'theforeman/dhcp'
mod 'camptocamp/systemd'
mod 'theforeman/tftp'
mod 'theforeman/git'
mod 'puppetlabs/xinetd'
mod 'example42/network'

mod 'puppet/gitlab'
mod 'puppet/r10k'

#moduledir 'modules/profile'

mod 'profile',
  :git => 'https://github.com/icinga/puppet-icinga2'
mod 'profile',
  :git => 'https://github.com/icinga/puppet-icingaweb2'
